### ISSUE TITLE
How often the Cloud IP-Range lists are requested?

### ISSUE THREAD

**Issue by matomoto** [matomo-org/plugin-TrackingSpamPrevention#109]
The TrackingSpamPrevention Plugin request 5 Cloud IP-Range lists on the Cloud servers.

amazon aws https://ip-ranges.amazonaws.com/ip-ranges.json

microsoft azure https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519

google digital ocean https://www.digitalocean.com/geo/google.csv

google cloud https://www.gstatic.com/ipranges/cloud.json

oracle cloud https://docs.cloud.oracle.com/en-us/iaas/tools/public_ip_ranges.json

The question is: How often, or at wich cycle point (tracking or create reports?), this Cloud IP-Range lists are requested?

A info is missing, that the Plugin requests this server, and how often.

**Comment by snake14** [comment]
Hi @matomoto . Looking at the [schedule of the task](https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/d3d68e88e6eee22465c5a83a0157d744c941f4f4/Tasks.php#L31), it appears that it's supposed to check the IP ranges daily (every 24 hours).

I'm closing this issue as answered, but please feel free to open it again if you need any further assistance.

**Comment by matomoto** [comment]
@snake14 , thanks for your answer. Further questions:

1.) Where are the IPs saved? In the database?

2.) At wich point the Plugin exclude this Visitors? Don't save it in the database as raw data? Or only exclude it by the creation of the reports?

**Comment by snake14** [comment]
Hi @matomoto I'm happy to help

1. The IP ranges are saved in the `option` table with the record name `TrackingSpamBlockedIpRanges`.
2. The plugin uses a couple hooks in the core tracker code and breaks out of the normal tracking processing before the visit is recorded in the database.

**Comment by matomoto** [comment]
@snake14 , thanks for your answer.

2.) Its good. Its prevent the saving of the bots in the database. But not all needed it so. She need the possibility to create reports with bots in the future. So, it was nice, to make it optionality. Then, a new/second way of blocking bots must be coded at the point of the creating of reports.

I prefer the non-saving of bots in the database. The suggestion is also not in my interest, but in common interest.

PS: Please check before if a user has the permission to reopen an closed issue. I don't have it.
