### ISSUE TITLE
Add instance URL in emails

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/plugin-TrackingSpamPrevention#136]
When having a lot of instances of Matomo running, from the emails you don't know which instance you got the alert from.
If you think this is a godd idea, I could open a pull request for it.

**Comment by mikkeschiren** [comment]
Pull request added:
https://github.com/matomo-org/plugin-TrackingSpamPrevention/pull/137

**Comment by snake14** [comment]
Hi @mikkeschiren . Thank you for taking the time to create this issue and submit a PR. I have approved your PR :+1:

**Comment by snake14** [comment]
Thank you again for your contribution @mikkeschiren . Your PR has been merged.

**Comment by Stan-vw** [comment]
Nice idea, thank you @mikkeschiren ❤️
