### ISSUE TITLE
Exclude user agents from load testing services

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-TrackingSpamPrevention#18]
eg `k6/0.31.1 (https://k6.io/)`.

We could exclude these automatically if they have excluded headless browsers. 

Not sure what other user agents are in use from various services.

We should also mention in the setting that this will exclude such load testing services when deactivating headless browsers.

Could also maybe check what user agents apache bench, jmeter, ... uses (if any). Just tested `ab` which uses eg `ApacheBench/2.3`.

Maybe we could even exclude `curl` and `wget`?

We could include here also some tools from security purposes like gobuster (which is also excluded in device detector but we might want to still exclude it here too).

**Comment by sgiehl** [comment]
@tsteur I have created a PR for device detector which will ensure that Matomo won't track requests from K6, as long as bots are disabled.

**Comment by tsteur** [comment]
@sgiehl will that be an issue if someone actually wants to load test Matomo?

**Comment by sgiehl** [comment]
@tsteur Using a custom user agent (which is support by most of those tools) will always circumvent the detection
