### ISSUE TITLE
Exclude user agents from server side tracking SDKs etc

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-TrackingSpamPrevention#19]
This might need to be a new setting from headless browsers because someone might want to disable headless browsers but not requests from server side libraries because the setting applies to all sites.

I mean eg requests like from Go HTTP Client `'go-http-client'`.

If someone is using only the JS tracker then this would be save to block requests from such clients.

**Comment by sgiehl** [comment]
We could use device detector for the detection and simply exclude all
detected libraries, which would be:
https://github.com/matomo-org/device-detector/blob/master/regexes/client/libraries.yml

**Comment by tsteur** [comment]
👍
