### ISSUE TITLE
Use GeoIP databases to detect cloud requests

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/plugin-TrackingSpamPrevention#3]
If someone is using a paid geoip database or an additional provider database, the geoip detection could actually be used to detect requests from some clouds.

Didn't check how accurate/updated their detections are in that case, but might be an option at least for those cloud providers that don't offer a list of ips we can import.

**Comment by tsteur** [comment]
It would maybe work. Depends on the provider though indeed and how often things are updated.

Eg tested `129.146.0.0` which belongs to oracle cloud. Maxmind detects `Oracle Cloud` as org but DB IP only detects `Oracle Corp`.

Using `47.254.32.0` which belongs to Alibaba Cloud then DB-IP gets it right but not MaxMind  (which only reports `Alibaba`).

I suppose there could be some manual checks though depending on the GeoIP provider.

**Comment by tsteur** [comment]
this is done
