### ISSUE TITLE
When an IP is banned, an HTTP 500 happens in the tracking request because it fails to send the email

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-TrackingSpamPrevention#32]
Getting this error:

![image](https://user-images.githubusercontent.com/273120/140196455-422847c4-99df-4a8b-84ef-078ed20cf0ed.png)

To reproduce, set max actions per visit for example to `3` and configure a notification email.

![image](https://user-images.githubusercontent.com/273120/140196524-1bb765a0-9ed1-4f09-bcad-c4ac265ce5fe.png)

Then issue 4 tracking requests. The 4th tracking request should result in an HTTP 500.

We noticed this yesterday ourselves as pretty much all tracking requests resulted in an HTTP 500 in one account.

The problem is that we shouldn't use twig to create the email in https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/BanIpNotificationEmail.php#L30

The email content is very basic anyway so we could instead simply create the email content in PHP directly.

For security we might want to call `Common::sanitizeInputValue($string)` for each of the values.

**Comment by tsteur** [comment]
@AltamashShaikh be great to look into this one soon.

**Comment by AltamashShaikh** [comment]
@tsteur will start working on this from tomorrow
