### ISSUE TITLE
Documentation of http-requests for detection of IP addresses from popular cloud providers

### ISSUE THREAD

**Issue by utrautmann** [matomo-org/plugin-TrackingSpamPrevention#34]
Hello,
some clients running Matomo in a DMZ from which no access to the Internet is permitted.
Every single access "from an inside server to the outside" must be activated in the firewall.
Is it possible that a list of server-urls requested by the plugin are documented? E.g. https://ip-ranges.amazonaws.com/?

**Comment by tsteur** [comment]
Sure @utrautmann We are requesting:

* https://ip-ranges.amazonaws.com/ip-ranges.json
* https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519
* https://digitalocean.com/geo/google.csv
* https://www.gstatic.com/ipranges/cloud.json
* https://docs.cloud.oracle.com/en-us/iaas/tools/public_ip_ranges.json

**Comment by mskf3000** [comment]
> Sure @utrautmann We are requesting:
> 
>     * https://ip-ranges.amazonaws.com/ip-ranges.json
> 
>     * https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519
> 
>     * https://digitalocean.com/geo/google.csv
> 
>     * https://www.gstatic.com/ipranges/cloud.json
> 
>     * https://docs.cloud.oracle.com/en-us/iaas/tools/public_ip_ranges.json

https://geoip.linode.com/
https://www.cloudflare.com/ips-v4
