### ISSUE TITLE
Digital Ocean's ip list seems offline

### ISSUE THREAD

**Issue by fbett** [matomo-org/plugin-TrackingSpamPrevention#66]
An error is thrown, when the cron is running:
Error Failed to retrieve digital ocean IP ranges for task 'Piwik\Plugins\TrackingSpamPrevention\Tasks.updateBlockedIpRanges'

There is an indicator, that the list is unavailable since multiple months:
https://www.digitalocean.com/community/questions/what-happened-to-the-digitalocean-ip-address-list

**Comment by AltamashShaikh** [comment]
Hey @fbett I can download "https://digitalocean.com/geo/google.csv".
I can also see we have set a timeout of `120 seconds` [here](https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/BlockedIpRanges/DigitalOcean.php#L19), may be check if the file download takes time from your server or is it blocked for your IP or something ?

**Comment by AltamashShaikh** [comment]
Hey ignore my previous comment file seems to be empty, I will check if I can find something else

**Comment by fbett** [comment]
Hi @AltamashShaikh 
You are right, i'm also able to download the list - but the file is empty

**Comment by AltamashShaikh** [comment]
Hey @fbett the empty response issue has been resolved by Digital Ocean, I will keep this issue open for a while for us to decide what to do in future if same problem arises.

**Comment by fbett** [comment]
Thanks a lot @AltamashShaikh!

**Comment by AltamashShaikh** [comment]
@fbett Just FYI, we have added a check to not throw exceptions if the file is empty. It will be released with the new version of plugin in couple of weeks mostly.
