### ISSUE TITLE
Digitial ocean IP list is no longer syncing

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-TrackingSpamPrevention#78]
Getting this error daily since Saturday

>  Scheduler: Error Failed to retrieve digital ocean IP ranges for task 'Piwik\Plugins\TrackingSpamPrevention\Tasks.updateBlockedIpRanges'

The URL `https://www.digitalocean.com/geo/google.csv` returns a not found page.

Because of this error the task no longer finishes (which is kind of on purpose so we notice such errors).

**Comment by snake14** [comment]
@tsteur How long ago did this error start? If it's recent, it could be related to [some DNS issues that DigitalOcean had](https://status.digitalocean.com/incidents/mstrkv8kv12j) over the weekend. The page is [still linked to on their page](https://docs.digitalocean.com/products/platform/). It also appears that [this page has had issues before](https://www.digitalocean.com/community/questions/what-happened-to-the-digitalocean-ip-address-list). Should we wait for a bit and see what happens or use an alternative?

**Comment by tsteur** [comment]
It started last Friday or Saturday. Sure we can wait for a few days we should just not forget. We'll likely receive daily emails about this so can also keep commenting from time to time about it

**Comment by AltamashShaikh** [comment]
Refer - https://github.com/matomo-org/plugin-TrackingSpamPrevention/pull/67 for previous fix

**Comment by AltamashShaikh** [comment]
FYI: I added a comment [here](https://www.digitalocean.com/community/questions/what-happened-to-the-digitalocean-ip-address-list) to notify digitalocean

**Comment by tsteur** [comment]
FYI it's still not working.

**Comment by AltamashShaikh** [comment]
Yes, and no reply on the forum too, the documentation still mentions this URL to download the required data though

**Comment by AltamashShaikh** [comment]
Just FYI, created a ticket on DigitalOcean as there was no reply on the blog comment

**Comment by sgiehl** [comment]
Just a general thought on that one. Should we maybe change the tests, so they work with dummy response data, and don't really send requests to the cloud providers? That would avoid failing tests.
To ensure that the URLs are still available we could also have a simply github action, that queries that urls and checks if the data still has the same format. Such an action could e.g. run daily or weekly.

**Comment by AltamashShaikh** [comment]
FYI, Just received a message from DigitalOcean that they have reported to the team internally and they are looking for a fix

**Comment by AltamashShaikh** [comment]
@tsteur Its up now and seems to download the CSV.
Can you check if the error is gone ?

**Comment by tsteur** [comment]
Awesome, thanks @AltamashShaikh . I suggest you close the issue and I can always comment again should I keep receiving errors about it.
