### ISSUE TITLE
Error Expected download URL for Azure IP ranges to start with HTTP but it does not

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-TrackingSpamPrevention#85]
For the last 2 days scheduled task failed to download Azure IP ranges. Getting this error:

> Scheduler: Error Expected download URL for Azure IP ranges to start with HTTP but it does not. It is: ttps://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20230116..json for task 'Piwik\Plugins\TrackingSpamPrevention\Tasks.updateBlockedIpRanges'

It should be trying to download https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20230116.json

It fails now daily.

**Comment by snake14** [comment]
The fix has been merged. @tsteur Does this need to be released sooner than our normal release cycle?

**Comment by tsteur** [comment]
@snake14 as it's a regression releasing it sooner be great 👍

**Comment by AltamashShaikh** [comment]
@tsteur will release a new version

**Comment by AltamashShaikh** [comment]
Released 4.1.5 version of the plugin

**Comment by snake14** [comment]
Thank you @AltamashShaikh . I forgot to do that yesterday.
